### PR TITLE
OSCServerDelegate protocol conforms to class

### PR DESCRIPTION
**Pull request by gwsounddsg**
This will allow the user to check equality on the OSCServerDelegate. For example:
```
class MyServer {
    let server: OSCServer

    init() {
        server = OSCServer(address: "localhost", port: 8080)
        server.delegate = self
    }
}

// in a Unit Test
func testDelegate() {
    let instance = MyServer()
    XCTAssertTrue(instance.server.delegate === instance)
}
```

As of Swift 5.1, this is the only way to check for equality between protocol by conforming them to `class`.

### CODE REVIEW

**Comment by gwsounddsg** [comment]
@devinroth do you know when you'll be pushing the master branch to the pod?

**Comment by devinroth** [comment]
I can do that today. Is there any other small changes you want to make first?

**Comment by gwsounddsg** [comment]
No, other than for some reason I can't get OSCServer to work at all. I'm sure this isn't the best place to mention that. I can create an issue, or we can chat about it another way. Whatever you'd prefer.

**Comment by devinroth** [comment]
Create and issue. We'll chat there.

**Pull request merged**
